apiVersion: v1
kind: Secret
metadata:
  name: skill-hire-secrets
  labels:
    app: skill-hire
type: Opaque
stringData:
  mongo-uri: mongodb+srv://moulisaideepget_db_user:88GVqr2zOr9WOIZ2@skillhire.lyjp15b.mongodb.net/hiring_application?retryWrites=true&w=majority
  aws-access-key: AKIAY6SGSHEAC3I3GNKK
  aws-secret-key: dueAhOMRvfGt5K5/dFfPT9ZzE1VsPRGMpKboPl0
  s3-bucket-name: skill-hire-profile-photos
  ses-sender-email: pediredlarishi2005@gmail.com
  admin-email: admin@skillhire.com
  admin-password: SkillHire@admin